# Generated by Django 5.1.6 on 2025-03-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(height_field=500, upload_to=None, width_field=500)),
            ],
        ),
    ]
